apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-iptables
        image: alpine
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache iptables
          iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-port 8000
          #iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 80 -j REDIRECT --to-port 8000
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: sidecar 
        image: sidecar 
        ports:
        - containerPort: 8000
