apiVersion: v1
kind: Pod
metadata:
  name: sample-service-pod
  labels:
    app: sample-service
spec:
  initContainers:
  - name: sidecar-init
    image: thecoolmanz/init
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  - name: service
    image: kennethreitz/httpbin
    ports:
    - containerPort: 80
  - name: proxy
    image: thecoolmanz/proxy
    ports:
    - containerPort: 8000