apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployments-scale
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments/scale
    resourceNames: ["nginx"]
    verbs:
      - update
      - patch
      - read
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-scale
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployments-scale
  apiGroup: rbac.authorization.k8s.io 
