scrape_configs:
  - job_name: "kubernetes-pods"
    basic_auth:
      username: prometheus
      password: prometheus
    kubernetes_sd_configs:
      - role: pod
    scrape_interval: 500ms
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container_name
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
